### model
model_name_or_path: ()
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: (/workspace/LLaMA-Factory/examples/deepspeed/ds_z2_config.json)

### dataset
dataset: ToolACE
template: llama3
cutoff_len: 8192
overwrite_cache: true
preprocessing_num_workers: 20
packing: false

### output
output_dir: ()
logging_steps: 1
save_steps: 0.99999
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
